// ─── PitLane mock call_log dataset (dashboard side) ─────────────────────────
//
// Single source of mock call data for /api/calls and /api/analytics. The
// shape matches the real Supabase `call_logs` row so callers don't need to
// branch on persistence mode.
//
// Aligned with src/lib/mock-customers (cust_001…cust_005 — same names) so
// caller_phone + customer_id resolve correctly across /calls, /customers,
// /analytics.
//
// When Phase 6 (CDK/Supabase live data) lands, the API routes flip off
// USE_MOCK_DATA and these stop being read.

import type { CallLogRow } from './supabase';

export const MOCK_CALLS: CallLogRow[] = [
    {
        id: 'call_001',
        caller_phone: '+16475550101',
        customer_id: 'cust_001',
        dealer_id: 'dealer_porsche_toronto',
        call_sid: null,
        conversation_id: null,
        direction: 'inbound',
        duration_secs: 187,
        summary: {
            outcome: 'appointment_booked',
            sentiment: 'positive',
            loaner_needed: false,
            topics: ['service appointment', 'recall 24V-271'],
            upsells_flagged: [{ type: 'brake_replacement', description: 'Rear Brake Replacement', value_est: 875 }],
            action_items: ['Book Annual Service B for May 28'],
            summary_text:
                'Customer called about 2021 Cayenne S. Discussed open recall 24V-271 (fuel injector). Annual Service B booked for May 28. Rear brake replacement declined again.',
            generated_by: 'openai',
        },
        transcript: null,
        status: 'completed',
        started_at: new Date(Date.now() - 3_600_000 * 2).toISOString(),
        ended_at: new Date(Date.now() - 3_600_000 * 2 + 187_000).toISOString(),
        created_at: new Date(Date.now() - 3_600_000 * 2).toISOString(),
    },
    {
        id: 'call_002',
        caller_phone: '+14165550202',
        customer_id: 'cust_002',
        dealer_id: 'dealer_porsche_toronto',
        call_sid: null,
        conversation_id: null,
        direction: 'inbound',
        duration_secs: 94,
        summary: {
            outcome: 'appointment_booked',
            sentiment: 'positive',
            loaner_needed: false,
            topics: ['oil change', 'noise complaint'],
            upsells_flagged: [{ type: 'cabin_air_filter', description: 'Cabin Air Filter', value_est: 240 }],
            action_items: ['Confirm 10:30 AM slot', 'Inspect front-end rattle'],
            summary_text:
                'Routine oil change inquiry. Confirmed 10:30 AM tomorrow. Customer mentioned front-end rattle — flagged for inspection.',
            generated_by: 'openai',
        },
        transcript: null,
        status: 'completed',
        started_at: new Date(Date.now() - 3_600_000 * 5).toISOString(),
        ended_at: new Date(Date.now() - 3_600_000 * 5 + 94_000).toISOString(),
        created_at: new Date(Date.now() - 3_600_000 * 5).toISOString(),
    },
    {
        id: 'call_003',
        caller_phone: '+14375550303',
        customer_id: 'cust_003',
        dealer_id: 'dealer_porsche_toronto',
        call_sid: null,
        conversation_id: null,
        direction: 'inbound',
        duration_secs: 243,
        summary: {
            outcome: 'inquiry',
            sentiment: 'neutral',
            loaner_needed: true,
            topics: ['RO status', 'loaner request'],
            upsells_flagged: [],
            action_items: ['Confirm completion by 4 PM', 'Arrange Cayenne loaner'],
            summary_text:
                'Checking status of Macan repair order. Brake fluid + 60K service in progress. Customer requested loaner — Cayenne or equivalent. ETA 4 PM.',
            generated_by: 'openai',
        },
        transcript: null,
        status: 'completed',
        started_at: new Date(Date.now() - 86_400_000).toISOString(),
        ended_at: new Date(Date.now() - 86_400_000 + 243_000).toISOString(),
        created_at: new Date(Date.now() - 86_400_000).toISOString(),
    },
    {
        id: 'call_004',
        caller_phone: '+15145550404',
        customer_id: 'cust_004',
        dealer_id: 'dealer_porsche_toronto',
        call_sid: null,
        conversation_id: null,
        direction: 'inbound',
        duration_secs: 132,
        summary: {
            outcome: 'upsell_flagged',
            sentiment: 'positive',
            loaner_needed: false,
            topics: ['718 Cayman tire wear', 'track preparation'],
            upsells_flagged: [{ type: 'track_tire_set', description: 'Michelin Cup 2 R tire set', value_est: 4200 }],
            action_items: ['Follow up in 4 weeks after travel'],
            summary_text:
                'Inquired about Cup 2 R tire set for upcoming track day at CTMP. Quoted $4,200 CAD. Interested but wants to schedule next month after return from travel.',
            generated_by: 'openai',
        },
        transcript: null,
        status: 'completed',
        started_at: new Date(Date.now() - 86_400_000 * 2).toISOString(),
        ended_at: new Date(Date.now() - 86_400_000 * 2 + 132_000).toISOString(),
        created_at: new Date(Date.now() - 86_400_000 * 2).toISOString(),
    },
    {
        id: 'call_005',
        caller_phone: '+16475457709',
        customer_id: 'cust_005',
        dealer_id: 'dealer_porsche_toronto',
        call_sid: null,
        conversation_id: null,
        direction: 'inbound',
        duration_secs: 68,
        summary: {
            outcome: 'issue_reported',
            sentiment: 'negative',
            loaner_needed: false,
            topics: ['warning light', 'diagnostic'],
            upsells_flagged: [],
            action_items: ['Book Monday diagnostic appointment'],
            summary_text:
                'GT3 RS intermittent warning light reported after Mosport track session. Diagnostic booked for Monday morning.',
            generated_by: 'openai',
        },
        transcript: null,
        status: 'completed',
        started_at: new Date(Date.now() - 86_400_000 * 3).toISOString(),
        ended_at: new Date(Date.now() - 86_400_000 * 3 + 68_000).toISOString(),
        created_at: new Date(Date.now() - 86_400_000 * 3).toISOString(),
    },
    // Two more recent calls to keep the analytics chart populated past the
    // 5-customer roster — same customers, different topics.
    {
        id: 'call_006',
        caller_phone: '+16475550101',
        customer_id: 'cust_001',
        dealer_id: 'dealer_porsche_toronto',
        call_sid: null,
        conversation_id: null,
        direction: 'outbound',
        duration_secs: 56,
        summary: {
            outcome: 'other',
            sentiment: 'positive',
            loaner_needed: false,
            topics: ['appointment reminder'],
            upsells_flagged: [],
            action_items: [],
            summary_text: 'Reminder call: Annual Service B confirmed for May 28, 8:30 AM.',
            generated_by: 'heuristic',
        },
        transcript: null,
        status: 'completed',
        started_at: new Date(Date.now() - 86_400_000 * 4).toISOString(),
        ended_at: new Date(Date.now() - 86_400_000 * 4 + 56_000).toISOString(),
        created_at: new Date(Date.now() - 86_400_000 * 4).toISOString(),
    },
    {
        id: 'call_007',
        caller_phone: '+14165550202',
        customer_id: 'cust_002',
        dealer_id: 'dealer_porsche_toronto',
        call_sid: null,
        conversation_id: null,
        direction: 'inbound',
        duration_secs: 312,
        summary: {
            outcome: 'appointment_booked',
            sentiment: 'positive',
            loaner_needed: true,
            topics: ['Taycan software update', 'loaner request', 'PDK fluid'],
            upsells_flagged: [{ type: 'detail_package', description: 'Full interior + exterior detail', value_est: 685 }],
            action_items: ['Book BMS update for June 18', 'Arrange Taycan loaner'],
            summary_text:
                'Booked Taycan in for BMS update + recall remediation on June 18. Loaner requested. Customer also asked about detailing package — quoted $685.',
            generated_by: 'openai',
        },
        transcript: null,
        status: 'completed',
        started_at: new Date(Date.now() - 86_400_000 * 6).toISOString(),
        ended_at: new Date(Date.now() - 86_400_000 * 6 + 312_000).toISOString(),
        created_at: new Date(Date.now() - 86_400_000 * 6).toISOString(),
    },
];
